# Generated by Django 3.1.5 on 2021-01-26 11:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(allow_unicode=True, max_length=64)),
                ('description', models.TextField(max_length=64, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(choices=[('Apr', 'Одобрено'), ('Pub', 'Опубликовано'), ('Del', 'Удалено'), ('Drf', 'Черновик')], default='Drf', max_length=32, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('slug', models.SlugField(allow_unicode=True, max_length=64)),
                ('text', models.TextField(verbose_name='Содержание')),
                ('status_update', models.DateField(default=datetime.date.today, verbose_name='Дата обновления статуса')),
                ('date_create', models.DateField(default=datetime.date.today, verbose_name='Дата создания статьи')),
                ('date_update', models.DateField(default=datetime.date.today, verbose_name='Дата изменения статьи')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.categorypost')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.statuspost')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(default=datetime.date.today)),
                ('date_update', models.DateField(default=datetime.date.today)),
                ('author_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Author_like', to=settings.AUTH_USER_MODEL)),
                ('post_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.post')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('date_create', models.DateField(default=datetime.date.today, verbose_name='Дата создания комментария')),
                ('date_update', models.DateField(default=datetime.date.today, verbose_name='Дата изменения комментария')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ответы', to='mainapp.comment')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
